### ISSUE TITLE
How does this work with THREE js?

### ISSUE THREAD

**Issue by danheywood** [cyrilf/vue-dat-gui#16]
Maybe I'm being dumb, but I'm implemented this into my Nuxt project as documented with HTML and Data() and used the data to set up the camera, but when I change the data using the sliders in dat.gui it does nothing. What am I missing? 

**HTML**
```
<dat-gui closeText="Close controls" openText="Open controls" closePosition="bottom">
        <dat-number v-model="cameraPos.x" :min="-10" :max="10" :step="0.01" label="Camera x"/>
        <dat-number v-model="cameraPos.y" :min="-10" :max="10" :step="0.01" label="Camera y"/>
        <dat-number v-model="cameraPos.z" :min="-10" :max="10" :step="0.01" label="Camera z"/>
</dat-gui>
```

**DATA**
```
export default {
  name: 'TheScene',
  data() {
    return {
      cameraPos: {
        x: -0.5,
        y: 3,
        z: 7
      }
    }
  },
```

**THREE JS**
```
this.camera.position.set(
      this.cameraPos.x,
      this.cameraPos.y,
      this.cameraPos.z
)
```

**Comment by cyrilf** [comment]
Hey,
First, I don't think you're dumb :)
Your code looks correct to me. I haven't checked this project in ages but my guess is that three.js isn't catching up on the `cameraPos` object updates?
Is it set up in a loop or something?

**Comment by danheywood** [comment]
Thank your for getting back to me so quickly! There’s a function that is constantly running in Three.js with requestAnimationFrame. So I tried redeclaring The camera positions in there which does update, however it is very choppy, not smooth like it would be normally.

**Comment by cyrilf** [comment]
Ok, then I don't know..
If you a live version of your code running online that might be helpful for me (or anyone else) to find out what's happening.

**Comment by danheywood** [comment]
Here you go
https://codesandbox.io/s/three-js-gi4x9

Hopefully that works for you, this is the first time I'm using Code Sandbox.

**Comment by danheywood** [comment]
Putting the below inside "handleTick()" makes it work.

```
this.camera.position.set(
      this.cameraPos.x,
      this.cameraPos.y,
      this.cameraPos.z
)
```

**Comment by cyrilf** [comment]
Thanks for the link.
The live preview you shared seems all fine and smooth to me.
Based on your previous comment I guess you solved it.
I'll close the issue, feel free to re-open if I misunderstood something.
