### ISSUE TITLE
Nuxt: The client-side rendered virtual DOM tree is not matching server-rendered content. 

### ISSUE THREAD

**Issue by vin-ni** [cyrilf/vue-dat-gui#26]
I further get this error in Nuxt:
<img width="827" alt="error" src="https://user-images.githubusercontent.com/9806572/124041316-f204ec80-da06-11eb-819b-0d27194bff6d.png">

It happens when i open the direct link that uses the plugin. If I go on the root page and navigate via nuxt, everything is fine and it loads. Not sure what could be causing this.

Maybe you have an idea :)
Thank you!

**Comment by cyrilf** [comment]
Hey,

Thanks for reporting that. Unfortunately I don't have the time at the moment to look into it.
Feel free to open a PR if you (or anyone) find a fix, I will appreciate that! :+1:

**Comment by vin-ni** [comment]
This is my current workaround:
``` 
<client-only>
   <dat-gui close-text="Close" open-text="Open" close-position="bottom">
  </client-only>`
