### ISSUE TITLE
Vue3 is not support

### ISSUE THREAD

**Issue by aladdin0414** [cyrilf/vue-dat-gui#63]
[Vue warn]: Property "$createElement" was accessed during render but is not defined on instance. 
  at <DatGui> 
  at <DatGUISample3> 
  at <App>

**Comment by cyrilf** [comment]
Hey @aladdin0414 ,

Sorry for the delay, this library wasn't maintained..
I've updated it to support Vue3.
Follow the [README](https://github.com/cyrilf/vue-dat-gui/blob/7a05c656fc1c04a332758d9f105403bca6d6e329/README.md) to find the instructions for Installing and Using it.
Let me know if you need help!
